### ISSUE TITLE
genesis_simple_menus_taxonomies filter has no effect

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-menus#4]
The provided filter has no effect:

~~~php
add_filter( 'genesis_simple_menus_taxonomies', 'gsm_sample_taxonomy' );
function gsm_sample_taxonomy( $taxonomies ) {
	$taxonomies[] = 'taxonomy-slug';
	return array_unique( $taxonomies );
}
~~~

Tested by:

1. Creating a new taxonomy called 'area' in AgentPress Listings.
2. Adding a term called 'North' to the area taxonomy.
3. Inserting the above code in Genesis Sample.
4. Changing 'taxonomy-slug' to 'area'.
5. Visiting the North term page.

Expected: "Navigation" section appears on term page with drop-down of all site menus.
Actual: No navigation section.

Changing `genesis-simple-menus/includes/class-genesis-simple-menus-term.php` from this…

~~~php
foreach( $this->taxonomies as $tax ) {
	add_action( "{$tax}_edit_form", array( $this, 'term_edit_form' ), 9, 2 );
}
~~~

…to this:

~~~php
foreach( $this->taxonomies as $tax ) {
	add_action( "{$tax}_edit_form", array( $this, 'term_edit_form' ), 9, 2 );
	add_action( "area_edit_form", array( $this, 'term_edit_form' ), 9, 2 );
}
~~~

…does result in a navigation section:

<img width="495" alt="edit_area_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/30223394-9dc55cdc-94c2-11e7-9fe0-668209040d42.png">

So the issue appears to be with the order of initialisation/hooks.

**Comment by nathanrice** [comment]
(Explaining the order of execution here)

1. The `Genesis_Simple_Menus` object is initialized at `plugins_loaded`.
2. The `Genesis_Simple_Menus_Term` object is initialized at `genesis_setup`.
3. Therefore the `genesis_simple_menus_taxonomies` filter runs at `genesis_setup`.

In a typical child theme, we call in the Genesis loader, which runs the `genesis_setup` hook. Anything in the child theme `functions.php` file that comes after that can't run on `genesis_setup`, since `genesis_setup` has already run.

So, I need to move the bit of code that registers/outputs new form fields to a later hook. In Genesis, we do it on `admin_init`, which seems like a good choice.

**Comment by nickcernis** [comment]
Confirmed!
- Menu appears in term archive settings:
    <img width="336" alt="edit_area_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/30617054-582b119e-9d8c-11e7-8d57-66debb42cbe6.png">
- Correct menu appears on term archive page.
